version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-pg:/docker-entrypoint-initdb.d

  bot:
    build: .
    image: genericon/baked-beans-bot
    environment:
      PGHOST: "db"
      PGUSER: "${PGUSER}"
      PGDATABASE: "${PGDATABASE}"
      PGPASSWORD: "${PGPASSWORD}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      WAIT_FOR_IT: "db:5432"
